"""Remove settings

Revision ID: 69d099745bef
Revises: a1d798a4b663
Create Date: 2026-03-19 14:16:05.920757

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers - used by alembic
revision = "69d099745bef"
down_revision = "a1d798a4b663"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uq_settings_name"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("name", mysql.VARCHAR(length=256), nullable=False),
        sa.Column(
            "value", mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"), nullable=False
        ),
        sa.Column(
            "created_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_date",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb3_uca1400_ai_ci",
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("uq_settings_name"), "settings", ["name"], unique=True)
    # ### end Alembic commands ###
