"""Template Init

Revision ID: a1d798a4b663
Revises:
Create Date: 2026-01-14 07:06:56.045024

"""

import sqlalchemy as sa
from alembic import op

# Revision identifiers - used by alembic
revision = "a1d798a4b663"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_logs",
        sa.Column("sender", sa.String(length=256), nullable=False),
        sa.Column("recipients", sa.String(length=1024), nullable=False),
        sa.Column("cc", sa.String(length=1024), nullable=True),
        sa.Column("bcc", sa.String(length=1024), nullable=True),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_html", sa.Boolean(), nullable=False),
        sa.Column("attachment_filenames", sa.String(length=256), nullable=True),
        sa.Column("reply_to", sa.String(length=256), nullable=True),
        sa.Column("redirected", sa.Boolean(), nullable=False),
        sa.Column("redirected_to", sa.String(length=1024), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_logs")),
    )
    op.create_table(
        "settings",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("name", name=op.f("uq_settings_name")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="role"), nullable=False),
        sa.Column("_password", sa.String(length=256), nullable=False),
        sa.Column("access_token", sa.String(length=32), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("num_logins", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("last_name", sa.String(length=256), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "modified_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("access_token", name=op.f("uq_users_access_token")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("email_logs")
    # ### end Alembic commands ###
