"""Users have usernames instead of emails

Revision ID: 16e4c4bc2be0
Revises: 69d099745bef
Create Date: 2026-03-19 15:26:33.249481

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers - used by alembic
revision = "16e4c4bc2be0"
down_revision = "69d099745bef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users")
    op.add_column("users", sa.Column("username", sa.String(length=256), nullable=False))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_last_name"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "email")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", mysql.VARCHAR(length=256), nullable=False))
    op.add_column("users", sa.Column("last_name", mysql.VARCHAR(length=256), nullable=False))
    op.add_column("users", sa.Column("email", mysql.VARCHAR(length=256), nullable=False))
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "username")
    # ### end Alembic commands ###
